title: The hadd awesome title
author: Simone the hadd 
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  this is my first attempt at using github pages. Its very exciting. And I can't wait to get started.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!
theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
